### ISSUE TITLE
Can't start GPIO Board

### ISSUE THREAD

**Issue by manuchi** [manuchi/PiLarm#1]
I've changed GPIO on line 21 because there was an error, now I can't start GPIO Board

**Comment by pedro-javierf** [comment]
Could you start the board before making changes?

**Comment by pedro-javierf** [comment]
Where is the problem? Uncommit if needed to restore to last version? (or create a 0.2 commit)

**Comment by pedro-javierf** [comment]
Solved in update 0.2P. I close.
